config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :users, only: [:show]
  root 'static_pages#home'

  get 'static_pages/home'
  get 'static_pages/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  validates :file, presence: true
  validates :title, presence: true
  scope :desc, -> {
    order("photos.id DESC")
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :avatar])
            devise_parameter_sanitizer.permit(:account_update, keys: [:email, :avatar])
        end
    # before_action :configure_permitted_parameters, if: :devise_controller?

    # protected

    #     def configure_permitted_parameters
    #         devise_parameter_sanitizer.for(:sign_up).push(:name, :surname,:username, :email, :avatar)
    #         devise_parameter_sanitizer.for(:account_update).push(:name, :surname, :email, :avatar)
    #     end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = current_user.photos.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.build(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to current_user, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.fetch(:photo, {}).permit(:description, :title, :file)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @photos = Photo.all
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @photos = @user.photos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def avatar_image
        if @user.avatar.attached?
            @user.avatar
        else
            image_url("avatar.jpg")
        end
    end
end

app/views/layouts/_gallery.html.erb
<div class="row">



  <% @photos.desc.each do |photo| %>
      <figure class="col-md-4" >
          <div class="hovereffect">
            <%= image_tag photo.file, class: "img-fluid", style: "height: 100%", alt: "picture"%>
              <div class="overlay">
                
                 <p>
                  <%= link_to photo.title, photo_path(photo) %>
                </p>
                <% if current_user.id == photo.user_id%>
                  <p>
                    <%= link_to "Edit", edit_photo_path(photo) %>
                  </p>
                  <p>
                    <%= link_to 'Delete', photo, method: :delete, data: {confirm: 'Are you sure?'} %>
                  </p>
                <% end %>
              </div>
              </div> 
        </figure>

  <% end %>

  <%# <div class="col-md-12">

    <div id="mdb-lightbox-ui"></div>

    <div class="mdb-lightbox  no-margin">

      <figure class="col-md-4 ">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(117).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(117).jpg"
            class="img-fluid">
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(98).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(98).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(131).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(131).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(123).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(123).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(118).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(118).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(128).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(128).jpg"

            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(115).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(115).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </div>   
         </div> 
        </a>
        
      </figure>
     
     
      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(128).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(128).jpg"

            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
            </div> 
        </a>
      </figure>

      <figure class="col-md-4">
        <a href="https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(115).jpg" data-size="1600x1067">
        <div class="hovereffect">
          <img alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(115).jpg"
            class="img-fluid" />
            <div class="overlay">
              <h2>Effect 12</h2>
                <p>
                  <a href="#">LINK HERE</a>
                </p>
            </div> 
        </div>   
         </div> 
        </a>
        
      </figure> %>




    <%# </div>
  </div>
 </div> %>
</div>

app/views/layouts/_navbar.html.erb
<nav>
      <%= link_to "Home",  static_pages_home_path, :class => "a" %>
      <%= link_to "Help",  static_pages_help_path, :class => "a" %>
      <% if user_signed_in? %>
            <%= link_to "Profile",  user_path(current_user), :class => "a" %>
            <%= link_to "Edit Profile", edit_user_registration_path, :class => "a" %>
            <%= link_to 'Add photo', new_photo_path, :class => "a" %>
            <%= link_to "Log out",  destroy_user_session_path, method: :delete, :class => "a" %>
        <% else %>
            <%= link_to "Log in", new_user_session_path, :class => "a"  %>
        <% end %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>MyTumoProject</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">








    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>

  <%= render 'layouts/navbar'%>

  <% if notice %>
  <p class="alert alert-success mb-0"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
 
    <%= yield %>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/photos/_form.html.erb
<div class="card mx-auto p-2  d-flex justify-content-center" style="width: 30rem; border: 2px solid black; margin-top: 50px; height: 33rem">
  <div class="card-body">
    <h2>Photo</h2>

    <%= form_with(model: photo, local: true) do |form| %>
      <div class="form-group" id="title">
        <%= form.label :title %><br />
        <%= form.text_field :title, autofocus: true%>
      </div>

      <div class="form-group" id="descr">
        <%= form.label :description %><br />
        <%= form.text_field :description %>
      </div>

      <%= form.file_field :file %>

      <div class="actions">
        <%= form.submit "Send" %>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/edit.html.erb
<%= render 'form', photo: @photo %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render 'form',  photo: @photo %>

app/views/photos/show.html.erb
<%= image_tag @photo.file, class: "img-fluid mx-auto d-block m-4", style: "height: 100%", alt: "picture"%>

<h1 class="text-center-1"> <%= @photo.title %> </h1>

<h3 class="text-center-1"><%= @photo.description %></h3>

app/views/static_pages/help.html.erb
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  
 <div class="carousel-inner">
    <div class="carousel-item active" data-interval="10000">
    <%= image_tag 'l.jpg', :class => "d-block w-100" %>
    </div>
    <div class="carousel-item" data-interval="2000">
    <%= image_tag 'pariz.jpg', :class => "d-block w-100" %>
    </div>
    <div class="carousel-item">
    <%= image_tag 'll.jpg', :class => "d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
<h2 class ="o">HELP</h2>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Developer</th>
      <th scope="col">age</th>
      <th scope="col">e-mail</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Khajak</td>
      <td>15</td>
      <td>khajak.ghazaryan.y@tumo.org</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Hayk</td>
      <td>16</td>
      <td>Sahakyan1434@gmail.com</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Gayane</td>
      <td>16</td>
      <td>gayane.o1.y@tumo.org</td>
    </tr>
  </tbody>
</table>

<!--card-->
<div class="cardHome">
<div class="card" style="width: 18rem;">
 <%= image_tag 'man1.png', :class => "card-img-top" %>
 
  <div class="card-body">
    <h4 class="card-title">Khajak Ghazaryan</h3>
<h4 class="card-title">Web Developer</h3>
    <p class="card-text">15 years old</p>
    <a href="https://www.google.com/gmail/about/" class="btn btn-primary">Gmail</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
 <%= image_tag 'woman1.png', :class => "card-img-top" %>
 
  <div class="card-body">
    <h4 class="card-title">Gayane Ohanjanyan</h3>
<h4 class="card-title">Web Developer</h3>
    <p class="card-text">16 years old</p>
    <a href="https://www.google.com/gmail/about/" class="btn btn-primary">Gmail</a>
  </div>
</div>


<div class="card" style="width: 18rem;">
 <%= image_tag 'man1.png', :class => "card-img-top" %>
 
  <div class="card-body">
    <h4 class="card-title">Hayk Sahakyan</h3>
<h4 class="card-title">Web Developer</h3>
    <p class="card-text">16 years old</p>
    <a href="https://www.google.com/gmail/about/" class="btn btn-primary">Gmail</a>
  </div>
</div>
</div>


</div>




<%# /////////////////// %>
<!-- Footer -->
<footer class="page-footer font-small cyan darken-3">

  <div class="container">

   
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 d-flex justify-content-center">
<a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
           <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
           <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
           <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
         
        </div>
      </div>

    </div>


  </div>


  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
     <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
     
    <% end %>

  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/static_pages/home.html.erb
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="10000">
    <%= image_tag 'l.jpg', :class => "d-block w-100" %>
    </div>
    <div class="carousel-item" data-interval="2000">
    <%= image_tag 'pariz.jpg', :class => "d-block w-100" %>
    </div>
    <div class="carousel-item">
    <%= image_tag 'll.jpg', :class => "d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>





<div class="container">
 

<%= render 'layouts/gallery'%>


</div>

<!-- Footer -->
<footer class="page-footer font-small cyan darken-3">

  <div class="container">

   
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 d-flex justify-content-center">
<a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
           <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
           <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
           <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
         
        </div>
      </div>

    </div>


  </div>


  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
     <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
     
    <% end %>

  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->





 

app/views/users/show.html.erb
<div class="view intro-2">
        <div class="full-bg-img">
            <div class="mask rgba-black-light flex-center">
                <div class="container text-center white-text">
                    <div class="white-text text-center wow fadeInUp">
                    <%= image_tag avatar_image, size: '250x250',class: 'rounded-circle mx-auto d-block'%>
                 <b><h1 class="h1"> <%= @user.email %> </h1></b>
                    </div>
                </div>
            </div>
        </div>
    </div>




 <%= render 'layouts/gallery'%>